# ---------- Identification du projet ----------
sonar.projectKey=dpscheck-frontend
sonar.projectName=DPSCHECK Frontend
sonar.projectVersion=1.0.0

# ---------- Serveur SonarQube ----------
sonar.host.url=http://localhost:9000

# ---------- Sources analysées ----------
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=\
    **/node_modules/**,\
    **/dist/**,\
    **/coverage/**,\
    **/.angular/**,\
    **/*.spec.ts,\
    **/environments/**,\
    **/main.ts,\
    **/polyfills.ts

# ---------- Encodage ----------
sonar.sourceEncoding=UTF-8
sonar.typescript.node=node

# ---------- Couverture de tests ----------
# Généré par Karma (angular.json → karmaConfig → coverageReporter)
sonar.javascript.lcov.reportPaths=coverage/dpscheck-frontend/lcov.info
sonar.typescript.lcov.reportPaths=coverage/dpscheck-frontend/lcov.info
sonar.coverage.exclusions=\
    **/*.spec.ts,\
    **/*.module.ts,\
    **/*.routes.ts,\
    **/app.config.ts,\
    **/environments/**,\
    **/main.ts,\
    **/core/models/**,\
    **/index.html

# ---------- Duplication ----------
sonar.cpd.exclusions=\
    **/core/models/**,\
    **/environments/**
