services:
  postgres-test:
    build:
      context: ./Backend/sql
      dockerfile: Dockerfile
    container_name: dpscheck_postgres_test
    restart: unless-stopped
    environment:
      POSTGRES_USER: dpscheck_test
      POSTGRES_PASSWORD: test_pwd
      POSTGRES_DB: dpscheck_test
    ports:
      # Port 5433 test
      - "5433:5432"
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dpscheck_test -d dpscheck_test" ]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - dpscheck_test_net

networks:
  dpscheck_test_net:
    driver: bridge
